### ISSUE TITLE
Kodi 19: Auto Complete Add On not integrated 

### ISSUE THREAD

**Issue by nchauley** [manfeed/skin.aeon.tajo#33]
Greetings. Not urgent however may be a feature for a future release:

In Kodi 18, The Auto Complete add-on could be selected in "Optional Add-Ons" however it is not an option in Kodi 19.
Needless to say, it really cuts down on keystrokes during searches on virtual keyboard!

_*Note: Tested and works in default Estuary skin._

Great skin and thanks for your consideration.

**Comment by manfeed** [comment]
I have just tested and it doesn't work well yet, even in Estuary, since when you select 'local' search in the Auto Complete options, you get an error message. It seems to work when you select 'Google' as the source, though, so I have decided to add back the option (it's already available in the last github version) for those advanced users that know how to install that addon in their own, but for the time being I won't be offering it under "Optional Add-Ons" since many users could think it's a skin bug when they get that error message. I will add it there when it works faultlessly.
