### ISSUE TITLE
request: add skip counter to info bar

### ISSUE THREAD

**Issue by howudodat** [manfeed/skin.aeon.tajo#84]
when skipping ahead or back, please add a small counter of current skip step, ie: +:10 +:30 +1:00
It's nice that the small marker advances on the progress bar when skipping, but having the actual number would help in jumping to a certain time

**Comment by manfeed** [comment]
I don't quite understand your request, since the progress bar already show the skip step. Each time you press [left] or [right] keys while watching a video the progress bar shows the skip step for one second or so. Anyway, I added a bigger label to the next version, so as to make it more visible...

![screenshot00001](https://user-images.githubusercontent.com/13109584/215466873-1f17bfd7-ff25-4126-9ff8-cc80ebd9414e.jpg)

**Comment by howudodat** [comment]
sorry, when I first posted this I wasn't as clear as I should have been, and I hadn't checked all of the overlays, I was referring to live tv:
![image](https://user-images.githubusercontent.com/3333605/215579148-60f39cc8-47d5-41af-99b5-170f48d29d73.png)

Also it would be nice to have comskip markers in the live tv (or recordings) overlay
